apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ff-front-ingress
  namespace: ff-production
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /frontfactory
        pathType: Prefix
        backend:
          service:
            name: ff-front-service
            port:
              number: 80

              
