apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-gateway-api
  namespace: ff-qualification
  labels:
    app: ff-gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-gateway-api
  template:
    metadata:
      labels:
        app: ff-gateway-api
    spec:
      containers:
        - name: ff-gateway-api
          image: nexus-registry.frontfactory.local/livrables-qualif/ff_gateway_api:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: TARGET_ENV
              value: PREPROD
            - name: JWT_AUDIENCE
              value: account
            - name: JWT_AUTHORITY
              value: http://10.4.202.5:8080/realms/frontfactory
      imagePullSecrets:
        - name: regcred
