apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-gateway-api
  namespace: ff-qualification
  labels:
    app: ff-gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-gateway-api
  template:
    metadata:
      labels:
        app: ff-gateway-api
    spec:
      containers:
        - name: ff-gateway-api
          image: nexus-registry.frontfactory.local/livrables-qualif/ff_gateway_api:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: TARGET_ENV
              value: PREPROD
            - name: JWT_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: ff-keycloak
                  key: JWT_AUTHORITY
                  optional: false
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: ff-keycloak
                  key: JWT_AUDIENCE
                  optional: false
      imagePullSecrets:
        - name: regcred
