apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ff-gateway-api-ingress
  namespace: ff-qualification
spec:
    ingressClassName: nginx
    rules:
      - host:
        http:
          paths:
            - pathType: Prefix
              backend:
                service:
                  name: ff-gateway-api-service
                  port:
                    number: 80
              path: /