apiVersion: v1
kind: Service
metadata:
  name: ff-gateway-api-service
  namespace: ff-qualification
  labels:
    app: ff-gateway-api
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
  selector:
    app: ff-gateway-api
  type: LoadBalancer
  loadBalancerIP: 10.4.202.3
  clusterIP: 10.104.180.95
