# traefik/config.yml
http:
  routers:
    traefik:
      rule: "Host(`traefik.frontfactory.local`)"
      service: "api@internal"
      tls:
        domains:
          - main: "docker.localhost"
            sans:
              - "*.docker.localhost"
          - main: "frontfactory.local"
            sans:
              - "*.frontfactory.local"

tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"
