apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-eshop-api
  namespace: ff-qualification
  labels:
    app: ff-eshop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-eshop-api
  template:
    metadata:
      labels:
        app: ff-eshop-api
    spec:
      containers:
        - name: ff-eshop-api
          image: nexus-registry.frontfactory.local/livrables-qualif/ff_eshop_api:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: ff-keycloak
                  key: JWT_AUDIENCE
                  optional: false
            - name: JWT_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: ff-keycloak
                  key: JWT_AUTHORITY
                  optional: false
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: ff-eshop-api
                  key: DB_CONNECTION_STRING
                  optional: false
            - name: PARSING_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ff-eshop-api
                  key: PARSING_BASE_URL
                  optional: false
            - name: GENERATOR_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ff-eshop-api
                  key: GENERATOR_BASE_URL
                  optional: false
            - name: AZURE_DEVOPS_API_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ff-eshop-api
                  key: AZURE_DEVOPS_API_BASE_URL
                  optional: false
            - name: AZURE_DEVOPS_ORGANIZATION
              valueFrom:
                secretKeyRef:
                  name: ff-eshop-api
                  key: AZURE_DEVOPS_ORGANIZATION
                  optional: false
            - name: AZURE_DEVOPS_PROJECT
              valueFrom:
                secretKeyRef:
                  name: ff-eshop-api
                  key: AZURE_DEVOPS_PROJECT
                  optional: false
            - name: AZURE_DEVOPS_PIPELINE_ID
              valueFrom:
                secretKeyRef:
                  name: ff-eshop-api
                  key: AZURE_DEVOPS_PIPELINE_ID
                  optional: false
            - name: AZURE_DEVOPS_AUTH_HEADER
              valueFrom:
                secretKeyRef:
                  name: ff-eshop-api
                  key: AZURE_DEVOPS_AUTH_HEADER
                  optional: false
      imagePullSecrets:
        - name: regcred
