apiVersion: v1
kind: Service
metadata:
  name: ff-jenkins-service
  namespace: ff-production
spec:
  ports:
    - name: httpport
      port: 80
      targetPort: 8080
    - name: jnlpport
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins