apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: nexus-registry.frontfactory.local/utilitaires/keycloak:18.0.0
          args: ["start-dev"]
          env:
            - name: KC_PROXY
              value: "edge"
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: ff-keycloak
                  key: KEYCLOAK_ADMIN
                  optional: false
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ff-keycloak
                  key: KEYCLOAK_ADMIN_PASSWORD
                  optional: false
            - name: KC_DB_URL
              valueFrom:
                secretKeyRef:
                  name: ff-keycloak
                  key: KC_DB_URL
                  optional: false
            - name: KC_DB
              valueFrom:
                secretKeyRef:
                  name: ff-keycloak
                  key: KC_DB
                  optional: false
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ff-keycloak
                  key: KC_DB_USERNAME
                  optional: false
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ff-keycloak
                  key: KC_DB_PASSWORD
                  optional: false
          ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
      imagePullSecrets:
        - name: regcred

