apiVersion: v1
kind: PersistentVolume
metadata:
  name: ff-preprod-keycloak-pv
  namespace: ff-qualification
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/ff-preprod-keycloak
    server: 10.4.201.160