version: '3.3'
services:
  deptrack:
    container_name: deptrack
    image: owasp/dependency-track
    restart: always
    networks:
      - proxy
    volumes:
      - /app/docker/volumes/dependencyTrack:/data
    labels:
      - traefik.http.routers.deptrack.rule=Host(`deptrack.frontfactory.local`)
      - traefik.enable=true
      - traefik.http.routers.deptrack.tls=true
      - traefik.http.services.deptrack.loadbalancer.server.port=8080
      - traefik.http.routers.deptrack.service=deptrack
networks:
  proxy:
    external: true
