apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-generation-api
  namespace: ff-production
  labels:
    app: ff-generation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-generation-api
  template:
    metadata:
      labels:
        app: ff-generation-api
        aadpodidbinding: pod-identity-aksfrontfactoryprod
    spec:
      containers:
        - name: ff-generation-api
          image: acrfrontfactoryprod.azurecr.io/livrables-production/ff_generation_api:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          command: ["/bin/sh", "-c", "export BASE_ANGULAR_DIR_LOCATION=$(cat /mnt/secrets-store/FF-GENERATION-BASE-ANGULAR-DIR-LOCATION) ;export CLIENT_FRONT_GENERATION_LOCATION=$(cat /mnt/secrets-store/FF-GENERATION-CLIENT-FRONT-GENERATION-LOCATION); export DB_CONNECTION_STRING=$(echo 'Data Source=ff-generation-db-service.ff-production.svc.cluster.local;Initial Catalog=ff_parsing;Persist Security Info=True;User ID=sa;Password='$(cat /mnt/secrets-store/FF-GENERATION-DB-PASSWORD)';'); export JWT_AUTHORITY=$(cat /mnt/secrets-store/FF-JWT-AUTHORITY); export JWT_AUDIENCE=$(cat /mnt/secrets-store/FF-JWT-AUDIENCE); export PARSING_BASE_URL=$(cat /mnt/secrets-store/FF-PARSING-BASE-URL); dotnet FrontFactory.Generator.Presentation.dll;"]
          volumeMounts:
            - name: secrets-store02-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
            - name: ffshare
              mountPath: "/mnt/ff-preprod-api-generation"
              readOnly: false
      volumes:
        - name: secrets-store02-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-akvfrontfactoryprod-podid"
        - name: ffshare
          azureFile:
            secretName: ffshare-secret
            shareName: ffshare
            readOnly: false