apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-generation-api
  namespace: ff-production
  labels:
    app: ff-generation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-generation-api
  template:
    metadata:
      labels:
        app: ff-generation-api
        aadpodidbinding: pod-identity-aksff
    spec:
      containers:
        - name: ff-generation-api
          image: acrff.azurecr.io/livrables-production/ff_generation_api:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          command: ["/bin/sh", "-c", "export JWT_AUTHORITY=$(cat /mnt/secrets-store/FF-JWT-AUTHORITY); export JWT_AUDIENCE=$(cat /mnt/secrets-store/FF-JWT-AUDIENCE); export PARSING_BASE_URL=$(cat /mnt/secret-store/FF-PARSING-BASE-URL); dotnet FrontFactory.Generator.Presentation.dll;"]
          volumeMounts:
            - name: secrets-store02-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store02-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-ffakv-podid"