apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-parsing-api
  namespace: ff-qualification
  labels:
    app: ff-parsing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-parsing-api
  template:
    metadata:
      labels:
        app: ff-parsing-api
    spec:
      containers:
        - name: ff-parsing-api
          image: nexus-registry.frontfactory.local/livrables-qualif/ff_parsing_api:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: ff-keycloak
                  key: JWT_AUDIENCE
                  optional: false
            - name: JWT_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: ff-keycloak
                  key: JWT_AUTHORITY
                  optional: false
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: ff-parsing-api
                  key: DB_CONNECTION_STRING
                  optional: false
            - name: GENERATOR_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ff-parsing-api
                  key: GENERATOR_BASE_URL
                  optional: false
            - name: CUSTOMER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ff-parsing-api
                  key: CUSTOMER_BASE_URL
                  optional: false
      imagePullSecrets:
        - name: regcred
