apiVersion: v1
kind: Service
metadata:
  name: ff-parsing-api-service
  namespace: ff-qualification
  labels:
    app: ff-parsing-api
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 80
    - port: 8081
      name: https
      targetPort: 443
  selector:
    app: ff-parsing-api
  type: LoadBalancer
