apiVersion: v1
kind: Service
metadata:
  name: keycloak2
  labels:
    app: keycloak2
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: keycloak2
  type: LoadBalancer