apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-eshop-api
  namespace: ff-production
  labels:
    app: ff-eshop-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-eshop-api
  template:
    metadata:
      labels:
        app: ff-eshop-api
        aadpodidbinding: pod-identity-aksfrontfactoryprodv2
    spec:
      containers:
        - name: ff-eshop-api
          image: acrfrontfactoryprod.azurecr.io/livrables-production/ff_eshop_api:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          command: ["/bin/sh", "-c", "export AZURE_DEVOPS_AUTH_HEADER=$(cat /mnt/secrets-store/AZURE-DEVOPS-AUTH-HEADER); export AZURE_DEVOPS_PIPELINE_ID=$(cat /mnt/secrets-store/AZURE-DEVOPS-PIPELINE-ID); export AZURE_DEVOPS_PROJECT=$(cat /mnt/secrets-store/AZURE-DEVOPS-PROJECT); export AZURE_DEVOPS_API_BASE_URL=$(cat /mnt/secrets-store/AZURE-DEVOPS-API-BASE-URL); export AZURE_DEVOPS_ORGANIZATION=$(cat /mnt/secrets-store/AZURE-DEVOPS-ORGANIZATION); export AZURE_DEVOPS_PIPELINE_DELETION_ID=$(cat /mnt/secrets-store/AZURE-DEVOPS-PIPELINE-DELETION-ID); export AZURE_DEVOPS_PIPELINE_DEPLOYMENT_ID=$(cat /mnt/secrets-store/AZURE-DEVOPS-PIPELINE-DEPLOYMENT-ID); export DB_CONNECTION_STRING=$(echo 'Data Source=ff-eshop-db-service.ff-production.svc.cluster.local;Initial Catalog=ff_customer;Persist Security Info=True;User ID=sa;Password='$(cat /mnt/secrets-store/FF-ESHOP-DB-PASSWORD)';'); export JWT_AUTHORITY=$(cat /mnt/secrets-store/FF-JWT-AUTHORITY); export JWT_AUDIENCE=$(cat /mnt/secrets-store/FF-JWT-AUDIENCE); export PARSING_BASE_URL=$(cat /mnt/secrets-store/FF-PARSING-BASE-URL); export GENERATOR_BASE_URL=$(cat /mnt/secrets-store/FF-GENERATOR-BASE-URL); dotnet FrontFactory.Customer.Presentation.dll;"]
          volumeMounts:
            - name: secrets-store05-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store05-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvaultff-podid"