apiVersion: v1
kind: Service
metadata:
  name: ff-parsing-db-service
  namespace: ff-production
spec:
  type: ClusterIP
  #type: LoadBalancer
  selector:
    app: ff-parsing-db
  ports:
    - port: 1433
      targetPort: 1433
      name: sqlport
