apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ff-preprod-db-eshop
spec:
  destination:
    name: 'ff-preprod-db-eshop'
    namespace: ff-qualification
    server: 'https://kubernetes.default.svc'
  source:
    path: Qualification/HELM/ff_eshop/ff_eshop_db
    repoURL: 'http://10.4.201.160:3000/frontfactory/FF_ENVIRONNEMENTS.git'
    targetRevision: master
  project: default
