apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ff-prod-db-parser
spec:
  destination:
    name: ''
    namespace: ff-production
    server: 'https://kubernetes.default.svc'
  source:
    path: Production/HELM/ff_parsing/ff_parsing_db
    repoURL: 'https://ProjetsD2022@dev.azure.com/ProjetsD2022/Projet%20fin%20de%20cycle%20-%20DI3%20%202022/_git/FrontFactory_Environnements'
    targetRevision: main
  project: default
