apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
        aadpodidbinding: pod-identity-aksff
    spec:
      containers:
        - name: keycloak
          image: acrff.azurecr.io/utilitaires/keycloak:18.0.0
          args: ["start-dev"]
          env:
          - name: KC_PROXY
            value: "edge"
          ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8443
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          command: ["/bin/sh", "-c", "export KEYCLOAK_ADMIN=$(cat /mnt/secrets-store/FF-KEYCLOAK-ADMIN); export KEYCLOAK_ADMIN_PASSWORD=$(cat /mnt/secrets-store/FF-KEYCLOAK-ADMIN-PASSWORD);"]
          volumeMounts:
            - name: secrets-store04-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store04-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-ffakv-podid"