apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-gateway-api
  namespace: ff-production
  labels:
    app: ff-gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-gateway-api
  template:
    metadata:
      labels:
        app: ff-gateway-api
    spec:
      containers:
        - name: ff-gateway-api
          image: acrff.azurecr.io/livrables-production/ff_gateway_api:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
          - name: JWT_AUTHORITY
            value: http://20.37.0.159:8080/realms/frontfactory
          - name: JWT_AUDIENCE
            value: account
          resources:
            requests:
              cpu: 250m
              memory: 750Mi