apiVersion: v1
kind: Service
metadata:
  name: ff-gateway-api-service
  namespace: ff-production
  labels:
    app: ff-gateway-api
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
  selector:
    app: ff-gateway-api
  type: LoadBalancer
  clusterIP: 10.0.7.162
  #loadBalancerIP: 20.213.242.133

