---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ff-keycloak-db-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-db
  template:
    metadata:
      labels:
        app: keycloak-db
        aadpodidbinding: pod-identity-aksff
    spec:
      containers:
        - name: keycloak-db
          image: postgres:10.1
          env:
          ports:
          - name: postgres
            containerPort: 5432
          command: ["/bin/sh", "-c", "export POSTGRES_DB=$(cat /mnt/secrets-store/FF-KEYCLOAK-POSTGRES-DB); export POSTGRES_USER=$(cat /mnt/secrets-store/FF-KEYCLOAK-POSTGRES-USER); export POSTGRES_PASSWORD=$(cat /mnt/secrets-store/FF-KEYCLOAK-POSTGRES-PASSWORD); /usr/lib/postgresql/10.1/bin/postgres -D /var/lib/postgresql/10.1/main -c config_file=/etc/postgresql/10.1/main/postgresql.conf;"]
          volumeMounts:
            - name: secrets-store09-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
            - name: ff-keycloak-db-pv
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: secrets-store09-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-akvfrontfactoryprod-podid"
        - name: ff-keycloak-db-pv
          persistentVolumeClaim:
            claimName: ff-keycloak-db-pvc