apiVersion: v1
kind: Service
metadata:
  name: keycloak-db-service
  labels:
    app: keycloak-db
spec:
  ports:
    - port: 5432
      name: postgres
      targetPort: 5432
  selector:
    app: keycloak-db
  type: LoadBalancer
  clusterIP: 10.0.7.166