---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ff-generation-db-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-generation-db
  namespace: ff-production
  labels:
    app: ff-generation-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-generation-db
  template:
    metadata:
      labels:
        app: ff-generation-db
        aadpodidbinding: pod-identity-aksfrontfactoryprod
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: ff-generation-db
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
          command: ["/bin/sh", "-c", "export SA_PASSWORD=$(cat /mnt/secrets-store/FF-GENERATION-DB-PASSWORD); /opt/mssql/bin/sqlservr;"]
          volumeMounts:
            - name: secrets-store06-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
            - mountPath: /var/opt/mssql
              name: ff-generation-db-pv
      volumes:
        - name: secrets-store06-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-akvfrontfactoryprod-podid"
        - name: ff-generation-db-pv
          persistentVolumeClaim:
            claimName: ff-generation-db-pvc
        