apiVersion: v1
kind: Service
metadata:
  name: ff-generation-db-service
  namespace: ff-production
spec:
  clusterIP: 10.0.238.122
  type: ClusterIP
  selector:
    app: ff-generation-db
  ports:
    - port: 1433
      targetPort: 1433
      name: sqlport
