---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ff-eshop-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-1
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-eshop-db
  namespace: ff-qualification
  labels:
    app: ff-eshop-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-eshop-db
  template:
    metadata:
      labels:
        app: ff-eshop-db
    spec:
      containers:
      - name: ff-eshop-db
        image: nexus-registry.frontfactory.local/utilitaires/mssql:latest
        ports:
          - containerPort: 1433
        env:
          - name: SA_PASSWORD
            value: Azerty@1234
          - name: ACCEPT_EULA
            value: "Y"
        volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: ff-eshop-db-pv
      volumes:
        - name: ff-eshop-db-pv
          persistentVolumeClaim:
            claimName: ff-eshop-db-pvc
      imagePullSecrets:
      - name: regcred