apiVersion: v1
kind: Service
metadata:
  name: ff-eshop-db-service
  namespace: ff-qualification
spec:
  type: LoadBalancer
  selector:
    app: ff-eshop-db
  ports:
    - port: 1433
      targetPort: 1433
      name: sqlport