apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-ffakv-podid
  namespace: ff-production
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"               
    keyvaultName: akvff       
    cloudName: ""                        
    objects:  |
      array:
        - |
          objectName: FF-ESHOP-DB-PASSWORD
          objectType: secret             
          objectVersion: ""
        - |
          objectName: FF-PARSING-DB-PASSWORD
          objectType: secret             
          objectVersion: "" 
        - |
          objectName: FF-JWT-AUTHORITY
          objectType: secret             
          objectVersion: "" 
        - |
          objectName: FF-JWT-AUDIENCE
          objectType: secret             
          objectVersion: "" 
        - |
          objectName: FF-KEYCLOAK-ADMIN
          objectType: secret             
          objectVersion: "" 
        - |
          objectName: FF-KEYCLOAK-ADMIN-PASSWORD
          objectType: secret             
          objectVersion: "" 
        - |
          objectName: FF-GATEWAY-TARGET-ENV
          objectType: secret             
          objectVersion: ""     
        - |
          objectName: FF-PARSING-BASE-URL
          objectType: secret             
          objectVersion: ""   
        - |
          objectName: FF-ESHOP-PARSING-BASE-URL
          objectType: secret             
          objectVersion: ""  
        - |
          objectName: FF-GENERATION-BASE-ANGULAR-DIR-LOCATION
          objectType: secret             
          objectVersion: ""  
        - |
          objectName: FF-GENERATION-CLIENT-FRONT-GENERATION-LOCATION
          objectType: secret             
          objectVersion: ""  
        - |
          objectName: FF-GENERATON-DB-PASSWORD
          objectType: secret             
          objectVersion: ""    
        
    tenantId: 14bc5219-40ca-4d62-a8e4-7c97c1236349