apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvaultff-podid
  namespace: ff-production
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"               
    keyvaultName: kvaultff       
    cloudName: ""                        
    objects:  |
      array:
        - |
          objectName: FF-ESHOP-DB-PASSWORD
          objectType: secret             
          objectVersion: ""
        - |
          objectName: FF-PARSING-DB-PASSWORD
          objectType: secret             
          objectVersion: "" 
        - |
          objectName: FF-GENERATION-DB-PASSWORD
          objectType: secret             
          objectVersion: "" 
        - |
          objectName: FF-JWT-AUDIENCE
          objectType: secret             
          objectVersion: "" 
        - |
          objectName: FF-JWT-AUTHORITY
          objectType: secret             
          objectVersion: "" 
        - |
          objectName: FF-KEYCLOAK-ADMIN
          objectType: secret             
          objectVersion: "" 
        - |
          objectName: FF-KEYCLOAK-ADMIN-PASSWORD
          objectType: secret             
          objectVersion: "" 
        - |
          objectName: FF-GENERATOR-BASE-URL
          objectType: secret             
          objectVersion: ""     
        - |
          objectName: FF-PARSING-BASE-URL
          objectType: secret             
          objectVersion: ""    
        - |
          objectName: FF-GENERATION-BASE-ANGULAR-DIR-LOCATION
          objectType: secret             
          objectVersion: ""  
        - |
          objectName: FF-GENERATION-CLIENT-FRONT-GENERATION-LOCATION
          objectType: secret             
          objectVersion: ""  
        - |
          objectName: AZURE-DEVOPS-API-BASE-URL
          objectType: secret             
          objectVersion: ""
        - |
          objectName: AZURE-DEVOPS-ORGANIZATION
          objectType: secret             
          objectVersion: ""
        - |
          objectName: AZURE-DEVOPS-PROJECT
          objectType: secret             
          objectVersion: ""
        - |
          objectName: AZURE-DEVOPS-AUTH-HEADER
          objectType: secret             
          objectVersion: ""
        - |
          objectName: AZURE-DEVOPS-PIPELINE-ID
          objectType: secret             
          objectVersion: ""
        - |
          objectName: AZURE-DEVOPS-PIPELINE-DEPLOYMENT-ID
          objectType: secret             
          objectVersion: ""
        - |
          objectName: AZURE-DEVOPS-PIPELINE-DELETION-ID
          objectType: secret             
          objectVersion: ""
    tenantId: 84c31ca0-ac3b-4eae-ad11-519d80233e6f