apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ff-jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-1
  resources:
    requests:
      storage: 5Gi
