apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-parsing-db
  namespace: ff-qualification
  labels:
    app: ff-parsing-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-parsing-db
  template:
    metadata:
      labels:
        app: ff-parsing-db
    spec:
      containers:
        - name: ff-parsing-db
          image: nexus-registry.frontfactory.local/utilitaires/mssql:latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ff-db
                  key: SA_PASSWORD
                  optional: false
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: ff-preprod-db-parsing-pv
      volumes:
        - name: ff-preprod-db-parsing-pv
          persistentVolumeClaim:
            claimName: ff-preprod-db-parsing-pvc
      imagePullSecrets:
        - name: regcred
