apiVersion: v1
kind: PersistentVolume
metadata:
  name: ff-preprod-db-parsing-pv
  namespace: ff-qualification
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/ff-preprod-db-parser
    server: 10.4.201.160
