apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-front
  namespace: ff-qualification
  labels:
    app: ff-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-front
  template:
    metadata:
      labels:
        app: ff-front
    spec:
      containers:
      - name: ff-front
        image: nexus-registry.frontfactory.local/livrables-qualif/front:latest
        ports:
           - name: http
             containerPort: 80
           - name: https
             containerPort: 443
        env:
          - name: parserApiBaseUrl
            value: ff-parsing-api-service.ff-qualification.svc.cluster.local
      imagePullSecrets:
      - name: regcred