apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-parsing-api
  namespace: ff-production
  labels:
    app: ff-parsing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-parsing-api
  template:
    metadata:
      labels:
        app: ff-parsing-api
    spec:
      containers:
        - name: ff-parsing-api
          image: acrff.azurecr.io/livrables-production/ff_parsing_api:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          command: ["/bin/sh", "-c", "export JWT_AUTHORITY=$(cat /mnt/secrets-store/FF-JWT-AUTHORITY); export JWT_AUDIENCE=$(cat /mnt/secrets-store/JWT_AUDIENCE); export DB_CONNECTION_STRING=$(echo 'Data Source=ff-parsing-db-service.ff-production.svc.cluster.local;Initial Catalog=ff_parsing;Persist Security Info=True;User ID=sa;Password='$(cat /mnt/secrets-store/FF-PARSING-DB-PASSWORD)';'); dotnet FrontFactory.Parser.Presentation.dll;"]
                volumeMounts:
                - name: secrets-store01-inline
                  mountPath: "/mnt/secrets-store"
                  readOnly: true
            volumes:
              - name: secrets-store01-inline
                csi:
                  driver: secrets-store.csi.k8s.io
                  readOnly: true
                  volumeAttributes:
                    secretProviderClass: "azure-ffakv-podid"