apiVersion: v1
kind: Service
metadata:
  name: ff-parsing-api-service
  namespace: ff-production
  labels:
    app: ff-parsing-api
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
  selector:
    app: ff-parsing-api
  type: ClusterIP
  ClusterIP: 10.0.7.165
