apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: 'benjamin.souhait@diiage.org'
    privateKeySecretRef:
      name: letsencrypt-account-key
    solvers:
    - dns01:
        webhook:
          groupName: 'letsencrypt'
          solverName: ovh
          config:
            endpoint: ovh-eu
            applicationKey: 'f157e03f72cece3b'
            applicationSecretRef:
              key: applicationSecret
              name: ovh-credentials
            consumerKey: '37697dd21d6cdff5237bf5624543ea80'
