apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-generation-api
  namespace: ff-qualification
  labels:
    app: ff-generation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-generation-api
  template:
    metadata:
      labels:
        app: ff-generation-api
    spec:
      containers:
        - name: ff-generation-api
          image: nexus-registry.frontfactory.local/livrables-qualif/ff_generation_api:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: JWT_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: ff-generation-api
                  key: JWT_AUDIENCE
                  optional: false
            - name: JWT_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: ff-generation-api
                  key: JWT_AUTHORITY
                  optional: false                 
            - name: DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: ff-generation-api
                  key: DB_CONNECTION_STRING
                  optional: false
            - name: PARSING_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: ff-generation-api
                  key: PARSING_BASE_URL
                  optional: false
            - name: BASE_ANGULAR_DIR_LOCATION
              valueFrom:
                secretKeyRef:
                  name: ff-generation-api
                  key: BASE_ANGULAR_DIR_LOCATION
                  optional: false
            - name: CLIENT_FRONT_GENERATION_LOCATION
              valueFrom:
                secretKeyRef:
                  name: ff-generation-api
                  key: CLIENT_FRONT_GENERATION_LOCATION
                  optional: false
          volumeMounts:
            - mountPath: /mnt/ff-preprod-api-generation
              name: ff-preprod-api-generation-pv
      volumes:
        - name: ff-preprod-api-generation-pv
          persistentVolumeClaim:
            claimName: ff-preprod-api-generation-pvc
      imagePullSecrets:
        - name: regcred
