apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-generation-api
  namespace: ff-qualification
  labels:
    app: ff-generation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-generation-api
  template:
    metadata:
      labels:
        app: ff-generation-api
    spec:
      containers:
        - name: ff-generation-api
          image: nexus-registry.frontfactory.local/livrables-qualif/ff_generation_api:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: BASE_ANGULAR_DIR_LOCATION
              value: /mnt/ff-preprod-api-generation/baseAngular
            - name: CLIENT_FRONT_GENERATION_LOCATION
              value: /mnt/ff-preprod-api-generation
            - name: JWT_AUDIENCE
              value: account
            - name: JWT_AUTHORITY
              value: http://10.4.202.5:8080/realms/frontfactory
            - name: PARSING_BASE_URL
              value: http://10.99.188.98/v1.0
            - name: DB_CONNECTION_STRING
              value: Data Source=ff-parsing-db-service.ff-qualification.svc.cluster.local;Initial Catalog=ff_generator;Persist Security Info=True;User ID=sa;Password=Azerty@1234;
          volumeMounts:
            - mountPath: /mnt/ff-preprod-api-generation
              name: ff-preprod-api-generation-pv
      volumes:
        - name: ff-preprod-api-generation-pv
          persistentVolumeClaim:
            claimName: ff-preprod-api-generation-pvc
      imagePullSecrets:
        - name: regcred
