apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff-generation-api
  namespace: ff-qualification
  labels:
    app: ff-generation-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ff-generation-api
  template:
    metadata:
      labels:
        app: ff-generation-api
    spec:
      containers:
        - name: ff-generation-api
          image: nexus-registry.frontfactory.local/livrables-qualif/ff_generation_api:latest
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
          volumeMounts:
            - mountPath: /mnt/ff-frontend-qualif
              name: ff-preprod-api-generation-pv
      volumes:
        - name: ff-preprod-api-generation-pv
          persistentVolumeClaim:
            claimName: ff-preprod-api-generation-pvc
      imagePullSecrets:
        - name: regcred
