apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ff-preprod-db-generation-pvc
  namespace: ff-qualification
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
