apiVersion: v1
kind: Service
metadata:
  name: ff-generation-db-service
  namespace: ff-qualification
spec:
  type: LoadBalancer
  loadBalancerIP: 10.4.202.7
  selector:
    app: ff-generation-db
  ports:
    - port: 1433
      targetPort: 1433
      name: sqlport
